---
 - name: Stop Zabbix Agent
      service:
        name: zabbix-agent
        state: stop

 - name: Stop Zabbix Agent
      service:
        name: zabbix-server
        state: stop
  
 - name: Criar diretorio Backup
    ansible.builtin.file:
      path: /tmp/zabbix-backup
      state: directory
      mode: '0755'
  
  - name: Copy file zbx-server
    ansible.builtin.copy:
      src: /etc/zabbix/zabbix_server.conf
      dest: /tmp/zabbix-backup
  
  - name: Copy file zbx-http
    ansible.builtin.copy:
      src: /etc/httpd/conf.d/zabbix.conf
      dest: /tmp/zabbix-backup

  - name: Copy dir. zbx-share
    ansible.builtin.copy:
      src: /usr/share/zabbix/
      dest: /tmp/zabbix-backup
  
  - name: Copy dir. zbx-share-doc
    ansible.builtin.copy:
      src: /usr/share/doc/zabbix-*
      dest: /tmp/zabbix-backup

  - name: Instalando Zabbix Agent
    shell: rpm -Uvh –force https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
     
  - name: Enabling repository front
    shell: yum-config-manager --enable zabbix-frontend
    
  - name: 
    yum:
      name: clean
        state: present
    
  - name: Realizado Upgrade Zabbix Server
    yum: name={{ item }} state=latest
    with_items:
      - zabbix-server-mysql
      - zabbix-web-mysql-scl
      - zabbix-nginx-conf-scl
      - zabbix-agent
      - zabbix-get
 
 - name: Configure Zabbix Server Web
   template:
     src: zabbix.conf.j2
     dest: /etc/zabbix/web/zabbix.conf.php
     mode: '0644'
   notify: restart zabbix-server  

 - name: Copy zabbix_server.conf template 
   template:
     src: templates/zabbix_server.conf.44.j2
     dest: /etc/zabbix/zabbix_server.conf
   notify: restart zabbix-server

 - name: Restart zabbix-server
   service:
     name: zabbix-server
     state: restarted

 - name: Copy zabbix_agentd.conf template 
   template:
     src: templates/zabbix_agentd.conf.44.j2
     dest: /etc/zabbix/zabbix_agentd.conf
   notify: restart zabbix-agent

 - name: restart php
   service:
     name: rh-php72-php-fpm
     state: restarted
 
 - name: restart nginx
   service:
     name: rh-nginx116-nginx
     state: restarted