---
- name: Stop Zabbix Agent
  ansible.builtin.service:
    name: zabbix-agent
    state: stopped

- name: Stop Zabbix Agent
  service:
    name: zabbix-server
    state: stopped
  
- name: Criar diretorio Backup
  ansible.builtin.file:
    path: /tmp/zabbix-backup
    state: directory
    mode: '0755'
  
- name: Copy file zbx-server
  ansible.builtin.copy:
    src: /etc/zabbix/zabbix_server.conf
    dest: /tmp/zabbix-backup
  
- name: Copy file zbx-http
  ansible.builtin.copy:
    src: /etc/httpd/conf.d/zabbix.conf
    dest: /tmp/zabbix-backup

#- name: Copy dir. zbx-share
#  ansible.builtin.copy:
#    src: /usr/share/zabbix/
#    dest: /tmp/zabbix-backup

- name: Remove repository (and clean up left-over metadata)
  yum_repository:
    name: zabbix-repo
    state: absent
  notify: yum-clean-metadata
  
- name: Install Zabbix Repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    file: "{{ item.file }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"

- name: Install Zabbix packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - zabbix-server-mysql
    - zabbix-web-mysql-scl
    - zabbix-nginx-conf-scl
    - zabbix-agent
    - zabbix-get 

- name: Configure Zabbix Server Web
  template:
    src: zabbix.conf.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: '0644'
  notify: restart zabbix-server  

- name: Copy zabbix_server.conf template 
  template:
    src: templates/zabbix_server.conf.44.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify: restart zabbix-server

- name: Restart zabbix-server
  service:
    name: zabbix-server
    state: restarted

- name: Copy zabbix_agentd.conf template 
  template:
    src: templates/zabbix_agentd.conf.44.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent

- name: restart php
  service:
    name: rh-php72-php-fpm
    state: restarted
 
- name: restart nginx
  service:
    name: rh-nginx116-nginx
    state: restarted
