---
- name: Stop Zabbix Agent
  ansible.builtin.service:
    name: zabbix-agent
    state: stopped

- name: Stop Zabbix Agent
  ansible.builtin.service:
    name: zabbix-server
    state: stopped

- name: Stop httpd
  ansible.builtin.service:
    name: httpd
    state: stopped
  ignore_errors: True
  
- name: Criar diretorio Backup
  ansible.builtin.file:
    path: /tmp/zabbix-backup
    state: directory
    mode: '0755'

- name: Dump database zabbix
  mysql_db:
    state: dump
    name: zabbix
    target: /tmp/zabbix.sql

- name: Copy dir. zabbix
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: "{{ zbx_dir }}", dest: '/tmp/' }

- name: Backup files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    backup: yes
  with_items:
    - { src: "{{ zbx_archive_server }}", dest: '/tmp/zabbix-backup' }
    - { src: "{{ zbx_archive_agent }}", dest: '/tmp/zabbix-backup' }
    - { src: /tmp/zabbix, dest: '/tmp/zabbix-backup' }
    - { src: "/tmp/zabbix.sql", dest: '/tmp/zabbix-backup' }
  ignore_errors: True

- name: Remove repository (and clean up left-over metadata)
  yum_repository:
    name: zabbix-repo
    state: absent
  notify: yum-clean-metadata
  
- name: Install Zabbix Repo.
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    file: "{{ item.file }}"
    baseurl: "{{ item.baseurl }}"
    enabled: "{{ item.enabled }}"
    gpgcheck: "{{ item.gpgcheck }}"
    gpgkey: "{{ item.gpgkey }}"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ zabbix_repo_yum }}"

- name: Install centos-release-scl
  yum:
    name: centos-release-scl
    state: present

- name: Remove versao web mysql 
  yum:
    name: "{{ item }}"
    state: removed
  with_items:
    - "{{ zbx_mysql }}"
    - "{{ zbx_web }}"

- name: Update Zabbix packages
  yum: 
    name: "{{ item }}" 
    state: latest
    update_only: yes
  with_items:
    - zabbix-server-mysql
    - zabbix-agent
    - zabbix-get

- name: Configure Zabbix Server Web
  template:
    src: zabbix.conf.j2
    dest: /etc/zabbix/web/zabbix.conf.php
    mode: '0644'
  notify: restart zabbix-server  

- name: Copy zabbix_server.conf template 
  template:
    src: templates/zabbix_server.conf.44.j2
    dest: /etc/zabbix/zabbix_server.conf
  notify: restart zabbix-server

- name: Restart zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted

- name: Copy zabbix_agentd.conf template 
  template:
    src: templates/zabbix_agentd.conf.44.j2
    dest: /etc/zabbix/zabbix_agentd.conf
  notify: restart zabbix-agent