---
- name: Update Zabbix-server
  hosts: all
  vars:
    zbx-mysql: zabbix-web-mysql-4.4.10-1.el7.noarch
    zbx-web: zabbix-web-4.4.10-1.el7.noarch
    zbx_database_password: ZabbixDB#2020!
    zbx_archive_server: '/etc/zabbix/zabbix_server.conf'
    zbx_archive_agent: '/etc/zabbix/zabbix_agentd.conf'
    zbx_archive_httpd: '/etc/httpd/conf.d/zabbix.conf'
    zbx_dir: '/usr/share/zabbix'
  become: yes
  roles:
  - zabbix-update
