---
zabbix_hostname: "{{ ansible_hostname }}"
mysql_port: 3306
zbx_server_address: 127.0.0.1
zbx_frontend_address: 127.0.0.1
zbx_database_address: 127.0.0.1
zbx_database_saas: False
zbx_database_name: zabbix
zbx_database_user: zabbix
zbx_database_password: ZabbixDB#2019!
# Zabbix Server parameters
zbx_start_pollers: 10
zbx_start_pollersunreachable: 10
zbx_start_trappers: 10
zbx_start_pingers: 10
zbx_timeout: 30
zbx_cache_size: 256M
zbx_value_cache_size: 256M
# Frontend parameters
time_zone: America/Sao_Paulo