---
zabbix_version: 5.0
zabbix_hostname: "{{ ansible_hostname }}"
mysql_port: 3306
zbx_server_address: 127.0.0.1
zbx_frontend_address: 127.0.0.1
zbx_database_address: 127.0.0.1
zbx_database_saas: False
zbx_database_name: zabbix
zbx_database_user: zabbix
zbx_database_password: ZabbixDB#2019!
zabbix_repo: zabbix
zabbix_repo_yum:
  - name: zabbix
    description: Zabbix Official Repository - $basearch
    file: zabbix
    baseurl: http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/
    enabled: 1 
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present
  - name: zabbix-frontend
    description: Zabbix Official Repository - $basearch
    file: zabbix
    baseurl: http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/frontend
    enabled: 1
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
  - name: zabbix-debuginfo
    description: Zabbix Official Repository - $basearch
    file: zabbix
    baseurl: http://repo.zabbix.com/zabbix/{{ zabbix_version }}/rhel/{{ ansible_distribution_major_version }}/$basearch/debuginfo
    enabled: 0
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present
  - name: zabbix-supported
    description: Zabbix Official Repository non-supported - $basearch
    baseurl: http://repo.zabbix.com/non-supported/rhel/{{ ansible_distribution_major_version }}/$basearch/
    file: zabbix
    enabled: 1
    gpgcheck: 0
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-ZABBIX
    state: present
# Zabbix Server parameters
zbx_start_pollers: 10
zbx_start_pollersunreachable: 10
zbx_start_trappers: 10
zbx_start_pingers: 10
zbx_timeout: 30
zbx_cache_size: 256M
zbx_value_cache_size: 256M
# Frontend parameters
time_zone: America/Sao_Paulo