---
- name: restart zabbix-server
  ansible.builtin.service:
    name: zabbix-server
    state: restarted

- name: restart zabbix-agent
  ansible.builtin.service:
    name: zabbix-agent
    state: restarted